default:
  image: golang:1.24

  cache:
    key:
      files:
        - go.mod
    paths:
      - .go/pkg/mod/

variables:
  GOPATH: $CI_PROJECT_DIR/.go

stages:
  - test
  - build

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

go-mod-tidy:
  stage: test
  script:
    - go mod tidy -diff

go-build:
  stage: build
  script:
    - go build
  artifacts:
    paths:
      - freedom-names
    expire_in: 1 week
